Mijn den haag
nl-design-system/gebruikersonderzoek pull request #46
Opened 2023-05-11 13:16 UTC by JeroenduC

onderzoek naar generieke services toegevoegd.

2023-05-11 14:56 UTC, Yolijn commented on docs/onderzoek-bekijken/mijn-zaken/denhaag-mijn-omgeving.md
> +Vrijwel a lie gebruikers zijn zich erg bewust van de risico's op phishing bij e-mail. Ze openen de notificatiemail wel als ze de afzender herkennen en het onderwerp logischerwijs van deze afzender ve
```suggestion
Vrijwel alle gebruikers zijn zich erg bewust van de risico's op phishing bij e-mail. Ze openen de notificatiemail wel als ze de afzender herkennen en het onderwerp logischerwijs van deze afzender verwachten.
```

2023-05-11 14:57 UTC, Yolijn commented on docs/onderzoek-bekijken/mijn-zaken/denhaag-mijn-omgeving.md
> +Dit geldt met name voor het doen van een beta ling. Een document uploaden vindt niet iedereen even makkelijk. Wanneer men iets moet aanleveren wil men ook graag vooraf weten wat er precies gevraagd w
```suggestion
Dit geldt met name voor het doen van een betaling. Een document uploaden vindt niet iedereen even makkelijk. Wanneer men iets moet aanleveren wil men ook graag vooraf weten wat er precies gevraagd wordt en waarom.
```

2023-05-11 15:02 UTC, Yolijn commented on docs/onderzoek-bekijken/mijn-zaken/denhaag-mijn-omgeving.md
> +Vooral op mobiel is het belangrijk dat de betekenis van de (waardevolle) lijst met contactmomenten sneller herkend wordt. Mogelijk is de toevoeging van enkele woorden als 'tijdlijn' of' uw eerderecon
```suggestion
Vooral op mobiel is het belangrijk dat de betekenis van de (waardevolle) lijst met contactmomenten sneller herkend wordt. Mogelijk is de toevoeging van enkele woorden als 'tijdlijn' of' uw eerdere contactmomenten over deze zaak' voldoende.
```

2023-05-11 15:02 UTC, Yolijn commented on docs/onderzoek-bekijken/mijn-zaken/denhaag-mijn-omgeving.md
> +Vooral op mobiel is het belangrijk dat de betekenis van de (waardevolle) lijst met contactmomenten sneller herkend wordt. Mogelijk is de toevoeging van enkele woorden als 'tijdlijn' of' uw eerderecon
```suggestion
Vooral op mobiel is het belangrijk dat de betekenis van de (waardevolle) lijst met contactmomenten sneller herkend wordt. Mogelijk is de toevoeging van enkele woorden als 'tijdlijn' of' uw eerdere contactmomenten over deze zaak' voldoende.
```

2023-05-11 15:05 UTC, Yolijn commented on docs/onderzoek-bekijken/mijn-zaken/denhaag-mijn-omgeving.md
> +- Er zijn vooral inwoners betrokken die minder don gemiddeld digivaardig en minder don gemiddeld taalvaardig zijn. Uitgangspunt was dot als zij met de Mijn-omgeving overweg kunnen, andere gebruikers
```suggestion
- Er zijn vooral inwoners betrokken die minder dan gemiddeld digivaardig en minder dan gemiddeld taalvaardig zijn. Uitgangspunt was dat als zij met de Mijn-omgeving overweg kunnen, andere gebruikers dat ook kunnen. Ter vergelijking zijn er twee respondenten met een hoog opleidingsniveau betrokken.
```

2023-05-11 15:05 UTC, Yolijn commented on docs/onderzoek-bekijken/mijn-zaken/denhaag-mijn-omgeving.md
> +- Respondenten zijn deels via een wervingsbureau geworven, deels via de taalschool waar de gemeente mee samenwerkt (voor laaggeletterde inwoners) en deels via een wijkproject in de Schilderswijk (voo
```suggestion
- Respondenten zijn deels via een wervingsbureau geworven, deels via de taalschool waar de gemeente mee samenwerkt (voor laaggeletterde inwoners) en deels via een wijkproject in de Schilderswijk (voor inzicht in de doelgroep die de Nederlandse taal minder goed beheerst).
```

2023-05-11 15:06 UTC, Yolijn commented on docs/onderzoek-bekijken/mijn-zaken/denhaag-mijn-omgeving.md
> +Let op: de test vond niet in een 'real life setting' plaats. De werkelijkheid is nagebootst door mensen zich te laten inleven in een scenario. Dit kan ervoor zorgen dot men bepaalde zaken in de testo
```suggestion
Let op: de test vond niet in een 'real life setting' plaats. De werkelijkheid is nagebootst door mensen zich te laten inleven in een scenario. Dit kan ervoor zorgen dat men bepaalde zaken in de testomgeving anders opvat dan wanneer men daadwerkelijk in de situatie zou zitten.
```

2023-05-11 15:07 UTC, Yolijn commented on docs/onderzoek-bekijken/mijn-zaken/denhaag-mijn-omgeving.md
> +- Bekijken taken: Bekijk wat er gevraagd wordt random jouw aanvraag voor subsidie voor geluidsisolatie (er hoeft niets uitgevoerd te warden).
```suggestion
- Bekijken taken: Bekijk wat er gevraagd wordt rondom jouw aanvraag voor subsidie voor geluidsisolatie (er hoeft niets uitgevoerd te worden).
```

2023-05-11 15:07 UTC, Yolijn commented on docs/onderzoek-bekijken/mijn-zaken/denhaag-mijn-omgeving.md
> +- Bekijken taken: Bekijk wat er gevraagd wordt random jouw aanvraag voor subsidie voor geluidsisolatie (er hoeft niets uitgevoerd te warden).
```suggestion
- Bekijken taken: Bekijk wat er gevraagd wordt rondom jouw aanvraag voor subsidie voor geluidsisolatie (er hoeft niets uitgevoerd te worden).
```

2023-05-11 15:08 UTC, Yolijn requested changes
@JeroenduC Ziet er behalve wat spelvautjus goed uit! Experimenteel heb ik de fouten als "suggestie" toegevoegd, misschien kun je dus gewoon op de knop drukken om de fix toe te voegen.

2023-05-12 07:56 UTC, JeroenduC commented
@Yolijn Volgens mij ging het grotendeeels goed! Er zijn een paar gevraagde changes outdated, misschien omdat ze dubbel waren? Die kan ik ook niet meer committen, omdat ze niet meer relevant zijn.

2023-05-12 09:16 UTC, Yolijn approved these changes

2023-05-12 09:16 UTC, merged