docs: onderzoek checklist 18 jaar toegevoegd
nl-design-system/gebruikersonderzoek pull request #48
Opened 2023-05-11 14:51 UTC by JeroenduC

2023-05-11 15:12 UTC, Yolijn commented on docs/onderzoek-bekijken/18-jaar worden/denhaag-checklist-18-jarigen.md
> +![](https://hackmd.io/_uploads/B1cZJKqVh.jpg)
alt-text voor dit plaatje mist :) 
```suggestion
![Verjaardagskaart met een taart met een nummer 18 kaarsje en de tekst "Regel je SHIT" erop](https://hackmd.io/_uploads/B1cZJKqVh.jpg)
```

2023-05-11 15:15 UTC, Yolijn commented on docs/onderzoek-bekijken/18-jaar worden/denhaag-checklist-18-jarigen.md
> +![](https://hackmd.io/_uploads/Sk9aAdc43.jpg)
```suggestion
![Binnenkant van kaart met checklist. Het eerste vakje met de tekst "checklist 18+ ontvangen" is aangevinkt. De rest van de acties zoals DigiD aanvragen is nog niet aangevinkt](https://hackmd.io/_uploads/Sk9aAdc43.jpg)
```

2023-05-11 15:24 UTC, Yolijn commented on docs/onderzoek-bekijken/18-jaar worden/denhaag-checklist-18-jarigen.md
> +  - utrecht
```suggestion
  - den haag
```

2023-05-11 15:24 UTC, Yolijn commented on docs/onderzoek-bekijken/18-jaar worden/denhaag-checklist-18-jarigen.md
> +  - gemeente utrecht
```suggestion
  - gemeente den haag
```

2023-05-11 15:25 UTC, Yolijn requested changes
Er missen alt beschrijvingen voor de images en ik vermoed dat de tags voor het denhaag bestand nog moeten worden veranderd :)

2023-05-12 07:57 UTC, JeroenduC commented on docs/onderzoek-bekijken/18-jaar worden/denhaag-checklist-18-jarigen.md
> +![](https://hackmd.io/_uploads/B1cZJKqVh.jpg)
Alt tekst vergeten! Dank je wel.,

2023-05-12 07:58 UTC, JeroenduC commented on docs/onderzoek-bekijken/18-jaar worden/utrecht-informatiecampagne-18-jaar copy.md
Klopt! Copy-paste foutje. :) Dank voor de spot!

2023-05-12 07:58 UTC, JeroenduC commented
@Yolijn Zoveel mogelijk met de button geprobeerd te fixen, er blijft helaas nog één outdated change open staan lijkt het.

2023-05-12 09:16 UTC, Yolijn approved these changes

2023-05-12 09:17 UTC, merged